services:
  - type: web
    name: luxury-hotel-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://ratanas1408_db_user:0JmJDgY6dV2CdOl4@cluster0.y9wzjmm.mongodb.net/hotel_management?retryWrites=true&w=majority&appName=Cluster0
